
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
# export RUSTFLAGS='-C link-self-contained=yes'
#, "-C", "link-arg=-lpthread"]
# "-C", "link-arg=-fuse-ld=lld"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
